/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["post_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Logout
         * @description 一律成功。session 早就過期的人也該把瀏覽器裡那張 cookie 清掉。
         */
        post: operations["post_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 門禁已經擋掉沒有 session 的請求，所以走到這裡一定有人。
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trending */
        get: operations["get_trending_api_discover_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Popular */
        get: operations["get_popular_api_discover_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["get_search_api_discover_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream
         * @description 一條 SSE 連線。斷線或關機時一定收掉訂閱。
         */
        get: operations["stream_api_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root Health */
        get: operations["read_root_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Detail
         * @description 上一輪的結果，逐服務與逐 Route。**不連任何服務**（`POST /health/check` 才連）。
         */
        get: operations["read_detail_api_health_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Check
         * @description 立刻重跑四項檢查（plan §3.2 的「+ 手動」）。迴圈跑的是同一支命令。
         */
        post: operations["post_check_api_health_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jobs
         * @description 下載列表，最新的在前面。
         */
        get: operations["get_jobs_api_jobs_get"];
        put?: never;
        /**
         * Post Job
         * @description 送一個 torrent 進 qBittorrent（plan §3.1、§3.3）。
         *
         *     **qBittorrent 收不下不是這一支的錯誤**：那時 Job 已經存在了，狀態是 `submit_failed`
         *     加上原文，而畫面上那一列有一顆重試（plan §3.1）。200 回的就是那一筆。
         */
        post: operations["post_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_hash}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Events
         * @description 時間線，最舊的在前面——讀的方向就是事情發生的方向。
         */
        get: operations["get_job_events_api_jobs__job_hash__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_hash}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Replan
         * @description 重新算一份 Plan（plan §6 jobs 群組、票 11）。
         *
         *     使用者按它的時刻是：Plan 停在 review 而他剛改了 Route 的設定，或 TMDB 那邊補上了正確的
         *     季集。回的是**那一筆 Job**（新的狀態與 `plan_id`）而不是 Plan 本身——按下去之後畫面上
         *     要重畫的是那一列。
         */
        post: operations["post_replan_api_jobs__job_hash__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_hash}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Retry
         * @description `submit_failed` → `requested` → 再送一次；`import_failed` → `importing`（plan §3.1）。
         */
        post: operations["post_retry_api_jobs__job_hash__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Media
         * @description 快照超過 24 小時就順手重抓（plan §8.3）。使用者不必按任何東西。
         */
        get: operations["get_media_api_media__media_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{media_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Refresh
         * @description 不管幾歲都重抓一次。TMDB 改了標題，`folder_name` 就跟著改（票 04b 驗收）。
         */
        post: operations["post_refresh_api_media__media_id__refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plans/{plan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Plan */
        get: operations["get_plan_api_plans__plan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Queries
         * @description 不打索引站，只讀快照——所以改 Route 時可以隨手重問。
         */
        get: operations["get_queries_api_search_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["get_search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Services
         * @description 三個服務現在的樣子。與健康頁同一份形狀——同一件事不該有兩種說法。
         */
        get: operations["get_services_api_settings_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/services/{kind}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Service Test
         * @description 「測試連線」：只重測這一個服務，其餘三項的結果留著（票 10）。
         */
        post: operations["post_service_test_api_settings_services__kind__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/qbittorrent/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qbittorrent Diff
         * @description 現值與建議值的逐鍵差異——與精靈第 4 步問的是同一個問題。
         */
        get: operations["get_qbittorrent_diff_api_settings_qbittorrent_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/qbittorrent/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Qbittorrent Apply
         * @description 「還原建議設定」。只寫有差異的鍵，跑的是精靈第 4 步的同一支命令。
         */
        post: operations["post_qbittorrent_apply_api_settings_qbittorrent_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Admin */
        post: operations["post_admin_api_setup_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Detect */
        post: operations["post_detect_api_setup_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/services/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Service
         * @description 既有服務的「測試連線」：存下連線資訊再連一次（plan §9.3 第 2 步）。
         */
        post: operations["post_service_api_setup_services__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jellyfin
         * @description 不連線，只回存下來的狀態。bootstrap 進行中前端輪詢這一支看序列走到哪裡。
         */
        get: operations["get_jellyfin_api_setup_jellyfin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Bootstrap
         * @description 套件內路徑：跑完 plan §9.4 的九步。重按只補做還沒做的那幾步。
         */
        post: operations["post_jellyfin_bootstrap_api_setup_jellyfin_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Connect
         * @description 既有路徑：登入、建立 API key、列出媒體庫（plan §9.5）。
         */
        post: operations["post_jellyfin_connect_api_setup_jellyfin_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/libraries/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Library Path
         * @description 既有路徑的「加入 Berth 路徑」。舊路徑原地不動（brief §16.4）。
         *
         *     失敗不是 4xx/5xx，而是回一條 `failed` 的 `libraries` 步驟——畫面靠它顯示原文與手動步驟。
         */
        post: operations["post_jellyfin_library_path_api_setup_jellyfin_libraries_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/plugin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Plugin
         * @description 既有路徑的「安裝 MergeVersions」。**會重啟 Jellyfin**，所以 UI 要二次確認。
         */
        post: operations["post_jellyfin_plugin_api_setup_jellyfin_plugin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/qbittorrent/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qbittorrent Diff
         * @description 現值與建議值的逐鍵差異。連得到才有內容，連不到就是 `reachable=false` 加原文。
         */
        get: operations["get_qbittorrent_diff_api_setup_qbittorrent_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/qbittorrent/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Qbittorrent Apply
         * @description 套用建議偏好。只寫有差異的鍵；勾了「同一組帳密」才順便設 WebUI 密碼。
         */
        post: operations["post_qbittorrent_apply_api_setup_qbittorrent_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Indexers */
        get: operations["get_indexers_api_setup_indexers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Indexers Apply
         * @description 套件內路徑：勾起來的站逐個加進 Prowlarr，逐站回報成敗。
         *
         *     對既有的索引站回 422：那是使用者自己的服務，Berth 只做檢查（brief §16.4）。
         */
        post: operations["post_indexers_apply_api_setup_indexers_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Indexers Connect
         * @description 既有路徑的「測試」。測不過也存，使用者才能改一個欄位再按一次。
         */
        post: operations["post_indexers_connect_api_setup_indexers_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Indexers Skip */
        post: operations["post_indexers_skip_api_setup_indexers_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/tmdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tmdb */
        get: operations["get_tmdb_api_setup_tmdb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/tmdb/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Tmdb Test
         * @description 先存再測。`configuration` 回得出來就證明這把憑證有效。
         *
         *     **沒有 `/tmdb/skip`**：這一步是閘門，測不過就走不到第 7 步（票 02b）。
         */
        post: operations["post_tmdb_test_api_setup_tmdb_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routes
         * @description 不連線，只回媒體庫清單與已經建好的 Route（含上一輪的檢查結果）。
         */
        get: operations["get_routes_api_setup_routes_get"];
        put?: never;
        /**
         * Post Routes
         * @description 建立 Route，並立刻建 category 與跑三項檢查（plan §9.5）。
         *
         *     檢查失敗**不是** 4xx：它是這一步的結果，逐項回在 `routes[].checks` 裡，畫面靠它顯示
         *     原文與該補哪個掛載。4xx 只留給「這個選擇本身無效」（不存在的媒體庫、不是它的路徑）。
         */
        post: operations["post_routes_api_setup_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Complete
         * @description 第 8 步：寫下 `settings.setup.completed`。**寫完這一支就要登入才進得來**（票 07）。
         */
        post: operations["post_complete_api_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminIn */
        AdminIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Apply To Services
             * @default true
             */
            apply_to_services?: boolean;
        };
        /**
         * CollectionType
         * @description Jellyfin 媒體庫的類型；沿用 Jellyfin 的字串（brief §4.3）。
         * @enum {string}
         */
        CollectionType: "movies" | "tvshows";
        /**
         * Confidence
         * @description brief §6.5 的三級。`HIGH` 與 `MEDIUM` 都自動入庫，`LOW` 進 review。
         * @enum {string}
         */
        Confidence: "high" | "medium" | "low";
        /**
         * ConnectIn
         * @description 既有服務的連線表單。每個服務只用得到其中幾個欄位。
         */
        ConnectIn: {
            /** Base Url */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key?: string;
            /**
             * Username
             * @default
             */
            username?: string;
            /**
             * Password
             * @default
             */
            password?: string;
        };
        /** DetectIn */
        DetectIn: {
            /**
             * Restart
             * @default false
             */
            restart?: boolean;
        };
        /**
         * DetectionReason
         * @description 判定的理由。UI 逐服務顯示，所以是封閉集合而不是自由文字。
         * @enum {string}
         */
        DetectionReason: "setup_pending" | "setup_completed" | "anonymous_ok" | "auth_required" | "ip_banned" | "no_indexers" | "has_indexers" | "api_key_missing" | "not_deployed" | "unreachable" | "protocol_mismatch" | "connected";
        /**
         * DiscoverItemOut
         * @description 牆上的一格。
         */
        DiscoverItemOut: {
            /** Id */
            id: string;
            /** Tmdb Id */
            tmdb_id: number;
            kind: components["schemas"]["MediaKind"];
            /** Title */
            title: string;
            /** Title En */
            title_en: string;
            /** Year */
            year: number | null;
            /** Poster Url */
            poster_url: string;
            /** Tracked */
            tracked: boolean;
        };
        /**
         * DiscoverOut
         * @description 一個 feed 的回應。
         *
         *     **失敗也是 200**：一頁上有三個 feed，其中一個拿不到 TMDB 時另外兩個照樣畫得出來，
         *     而畫面要說得出下一步。把它做成 HTTP 錯誤的話，前端只剩一個狀態碼，分不出
         *     「還沒填憑證」與「TMDB 連不上」——那兩件事的修法完全不同（票 03 驗收）。
         */
        DiscoverOut: {
            /** Items */
            items: components["schemas"]["DiscoverItemOut"][];
            problem: components["schemas"]["TmdbProblem"] | null;
            /** Detail */
            detail: string;
        };
        /**
         * EpisodeOut
         * @description 一集。
         */
        EpisodeOut: {
            /** Episode Number */
            episode_number: number;
            /** Name */
            name: string;
            /** Air Date */
            air_date: string | null;
            /** Runtime */
            runtime: number | null;
            /** Absolute Number */
            absolute_number: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Setup Completed */
            setup_completed: boolean;
        };
        /**
         * HealthDetailOut
         * @description 四項檢查的明細。健康頁與設定頁讀的是同一份——同一件事不該有兩種說法。
         */
        HealthDetailOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checked At */
            checked_at: string | null;
            /** Interval Seconds */
            interval_seconds: number;
            /** Services */
            services: components["schemas"]["ServiceHealthOut"][];
            routes_status: components["schemas"]["HealthStatus"];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            poller: components["schemas"]["PollerOut"];
        };
        /**
         * HealthStatus
         * @description Route 或服務的最後檢查結果；`UNKNOWN` 表示尚未檢查過。
         * @enum {string}
         */
        HealthStatus: "unknown" | "ok" | "failed";
        /** IndexerApplyIn */
        IndexerApplyIn: {
            /**
             * Indexers
             * @default []
             */
            indexers?: string[];
        };
        /**
         * IndexerConnectIn
         * @description 既有路徑：Prowlarr 位址 + key，或任意 Torznab 端點 + key。
         */
        IndexerConnectIn: {
            kind: components["schemas"]["IndexerKind"];
            /** Base Url */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key?: string;
        };
        /**
         * IndexerKind
         * @description 第 5 步接索引站的兩種方式（plan §8.4、§9.3 第 5 步）。
         * @enum {string}
         */
        IndexerKind: "prowlarr" | "torznab";
        /** IndexerOptionOut */
        IndexerOptionOut: {
            /** Definition Name */
            definition_name: string;
            /** Name */
            name: string;
            /** Privacy */
            privacy: string;
            /** Present */
            present: boolean;
        };
        /**
         * IndexerProblem
         * @description 索引站那邊沒搜到東西的五種樣子（票 08 的結果表）。
         *
         *     與 `TmdbProblem` 同一個道理：分成五種而不是一句錯誤訊息，是因為**下一步不同**。
         *     索引站是精靈裡唯一可以跳過的一步，所以 `not_configured` 不是失敗而是「還沒接」——
         *     畫面要把人送回泊位 5，不是叫他重試。
         * @enum {string}
         */
        IndexerProblem: "not_configured" | "no_query" | "no_search" | "credential_rejected" | "unreachable";
        /** IndexerSetupOut */
        IndexerSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            kind: components["schemas"]["IndexerKind"];
            /** Base Url */
            base_url: string;
            /** Api Key Present */
            api_key_present: boolean;
            /** Reachable */
            reachable: boolean;
            /** Options */
            options: components["schemas"]["IndexerOptionOut"][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Skipped */
            skipped: boolean;
            /** Sets Password */
            sets_password: boolean;
            /** Error */
            error: string;
        };
        /**
         * JellyfinConnectIn
         * @description 既有 Jellyfin 的管理員帳密。只用來換 API key，不存下來。
         */
        JellyfinConnectIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** JellyfinSetupOut */
        JellyfinSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            /** Api Key Present */
            api_key_present: boolean;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Merge Versions Installed */
            merge_versions_installed: boolean;
            /** Merge Movies Task Id */
            merge_movies_task_id: string;
            /** Merge Episodes Task Id */
            merge_episodes_task_id: string;
        };
        /** JobCreateIn */
        JobCreateIn: {
            source: components["schemas"]["JobSourceIn"];
            /** Media */
            media: string;
            /** Route */
            route: number;
        };
        /**
         * JobCreatedOut
         * @description 送單的結果。
         *
         *     `created` 分得出「送出去了」與「這一個本來就在了」（plan §3.3）。兩者都是 200——
         *     使用者按第二次時要看到的是那一筆既有的 Job，不是一則錯誤。
         */
        JobCreatedOut: {
            job: components["schemas"]["JobOut"];
            /** Created */
            created: boolean;
        };
        /**
         * JobEventOut
         * @description 時間線上的一筆（brief §5.2）。
         */
        JobEventOut: {
            /** Id */
            id: number;
            /** Type */
            type: string;
            /** Actor */
            actor: string;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * JobOut
         * @description 下載列表與 Job 詳情上的一筆。
         */
        JobOut: {
            /** Hash */
            hash: string;
            /** Name */
            name: string;
            state: components["schemas"]["JobState"];
            trigger: components["schemas"]["JobTrigger"];
            /** Trigger Ref */
            trigger_ref: string;
            /** Error */
            error: string;
            /** Media Id */
            media_id: string | null;
            /** Media Title */
            media_title: string;
            /** Route Id */
            route_id: number | null;
            /** Route Name */
            route_name: string;
            /** Route Slug */
            route_slug: string;
            /** User Id */
            user_id: number | null;
            /** User Name */
            user_name: string;
            /** Save Path */
            save_path: string;
            /** Content Path */
            content_path: string;
            /** Total Size */
            total_size: number;
            /** Progress */
            progress: number;
            /** Client State */
            client_state: string;
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Imported At */
            imported_at: string | null;
            /** Retryable */
            retryable: boolean;
            /** Replannable */
            replannable: boolean;
            /** Plan Id */
            plan_id: number | null;
        };
        /**
         * JobSourceIn
         * @description 結果表那一列帶過來的東西。
         *
         *     **不是一個結果 id**：搜尋結果不落地（票 08），所以送單時前端要把那一列本身送回來。
         *     `url` 尤其如此——Prowlarr 的代理連結每次搜尋都不一樣（brief §20.7），只有使用者
         *     眼前那一輪的那一條是有效的。
         */
        JobSourceIn: {
            /** Url */
            url: string;
            /** Title */
            title: string;
            /**
             * Info Hash
             * @default
             */
            info_hash?: string;
        };
        /**
         * JobState
         * @description 一個 Job 的生命週期位置（plan §3.1、brief §5.1）。
         *
         *     宣告順序就是狀態機的主幹，分支緊接在它離開的那一站之後。**這一票只走得到前三個**：
         *     `requested` 是 `add_download` 建出來的，qBittorrent 收下就是 `submitted`，收不下是
         *     `submit_failed`。其餘由票 10 起的迴圈驅動——先一次定義完是因為它們是同一個封閉集合，
         *     分兩批加的話畫面上的狀態字典會有兩份，而其中一份遲早會漏掉一個狀態。
         * @enum {string}
         */
        JobState: "requested" | "submitted" | "submit_failed" | "metadata_ready" | "downloading" | "stalled" | "missing_files" | "client_error" | "client_removed" | "completed" | "planning" | "review" | "importing" | "imported" | "import_failed" | "removed";
        /**
         * JobTrigger
         * @description 這個 Job 是誰要的（`CONTEXT.md`、plan §2.3）。
         *
         *     規則 id 與重新入庫的來源目錄放在 `jobs.trigger_ref`，不編進這個字串——畫面要拿它
         *     分組，而 `rss:12` 那種寫法會讓每一條規則各自成為一種 trigger。
         * @enum {string}
         */
        JobTrigger: "manual" | "rss" | "reimport";
        /** LibraryChoiceOut */
        LibraryChoiceOut: {
            /** Name */
            name: string;
            /** Collection Type */
            collection_type: string;
            /** Locations */
            locations: string[];
            /** Berth Path */
            berth_path: string;
            /** Has Berth Path */
            has_berth_path: boolean;
            /** Uses Tvdb */
            uses_tvdb: boolean;
            /** Supported */
            supported: boolean;
            /** Selected */
            selected: boolean;
            /** Target Path */
            target_path: string;
            profile: components["schemas"]["Profile"];
        };
        /** LibraryOut */
        LibraryOut: {
            /** Name */
            name: string;
            /** Collection Type */
            collection_type: string;
            /** Locations */
            locations: string[];
            /** Metadata Fetchers */
            metadata_fetchers: string[];
            /** Uses Tvdb */
            uses_tvdb: boolean;
            /** Berth Path */
            berth_path: string;
            /** Has Berth Path */
            has_berth_path: boolean;
        };
        /** LibraryPathIn */
        LibraryPathIn: {
            /** Library */
            library: string;
        };
        /**
         * LoginIn
         * @description 帳密**不加約束、也不設必填**：少一個欄位就會是 422，而 422 與 401 分得出來就是一個
         *     可以拿來試探的差別。空的與錯的一律交給 services 拒絕，回同一個 401。
         *
         *     422 的回應本身不帶收到的值——那是 `api/errors.py` 的事。
         */
        LoginIn: {
            /**
             * Username
             * @default
             */
            username?: string;
            /**
             * Password
             * @default
             */
            password?: string;
        };
        /**
         * MappingStrategy
         * @description 季集是**怎麼**決定的（plan §4.2 的 `Candidate.strategy`）。
         *
         *     這個欄位不是註解：`review` 佇列靠它分組，benchmark 靠它回答「哪一條規則在賺錢、
         *     哪一條在賠錢」，而信心的上限也是逐條策略定的（brief §6.5）。
         * @enum {string}
         */
        MappingStrategy: "explicit" | "folder" | "context" | "arc_name" | "single_season" | "absolute_group" | "absolute_cumulative" | "air_date_offset" | "cour_offset" | "movie";
        /**
         * MeOut
         * @description 使用者可見的身分。id 與 Jellyfin user id 都不外流——UI 用不到。
         */
        MeOut: {
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
        };
        /**
         * MediaKind
         * @description 一個作品是劇集還是電影（plan §2.2）。
         *
         *     字串同時是三個東西：`media.id` 的前綴（`tv:1234`）、TMDB `search/multi` 回的
         *     `media_type`，以及 TMDB 那兩組端點的路徑段（`trending/tv/week`、`movie/popular`）。
         *     三者一致不是巧合——沿用 provider 的字串就不必維護一張對照表。
         * @enum {string}
         */
        MediaKind: "tv" | "movie";
        /**
         * MediaOut
         * @description 詳情頁的一整份。
         *
         *     **拿不到 TMDB 時仍然是 200**，理由放在 `problem`（與探索頁同一個 enum）：存下來的
         *     快照過期了但仍然是真的季集，畫得出來就該畫出來，只是要說一句「這是舊的」（票 04）。
         */
        MediaOut: {
            /** Id */
            id: string;
            /** Tmdb Id */
            tmdb_id: number;
            kind: components["schemas"]["MediaKind"];
            /** Title */
            title: string;
            /** Title En */
            title_en: string;
            /** Title Original */
            title_original: string;
            /** Year */
            year: number | null;
            /** First Air Date */
            first_air_date: string | null;
            /** Overview */
            overview: string;
            /** Poster Url */
            poster_url: string;
            /** Runtime */
            runtime: number | null;
            /** Folder Name */
            folder_name: string;
            /** Folder Frozen */
            folder_frozen: boolean;
            /** Tracked */
            tracked: boolean;
            /** Default Route Id */
            default_route_id: number | null;
            /** Seasons */
            seasons: components["schemas"]["SeasonOut"][];
            /** Fetched At */
            fetched_at: string | null;
            /** Routes */
            routes: components["schemas"]["RouteChoiceOut"][];
            problem: components["schemas"]["TmdbProblem"] | null;
            /** Detail */
            detail: string;
        };
        /**
         * PlanAction
         * @description 一個檔案的處置（plan §2.3 的 `plan_items.action`）。
         * @enum {string}
         */
        PlanAction: "import" | "extra" | "subtitle" | "skip" | "unmatched" | "review";
        /**
         * PlanEngine
         * @description 這一份 Plan 是誰算的（plan §2.3 的 `plans.engine`、brief §5.2）。
         * @enum {string}
         */
        PlanEngine: "rules" | "ai" | "user";
        /**
         * PlanItemOut
         * @description Plan 表格上的一列（brief §6.5：決定、信心與理由）。
         */
        PlanItemOut: {
            /** Id */
            id: number;
            /** Rel Path */
            rel_path: string;
            action: components["schemas"]["PlanAction"];
            /** Media Id */
            media_id: string | null;
            /** Season */
            season: number | null;
            /** Episode Start */
            episode_start: number | null;
            /** Episode End */
            episode_end: number | null;
            /** Target Path */
            target_path: string;
            confidence: components["schemas"]["Confidence"];
            /** Reasons */
            reasons: string[];
            /** Audit */
            audit: boolean;
            /** Error */
            error: string;
        };
        /**
         * PlanOut
         * @description 一份 Plan。
         */
        PlanOut: {
            /** Id */
            id: number;
            /** Job Hash */
            job_hash: string | null;
            status: components["schemas"]["PlanStatus"];
            engine: components["schemas"]["PlanEngine"];
            /** Engine Version */
            engine_version: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            summary: components["schemas"]["PlanSummary"];
            /** Items */
            items: components["schemas"]["PlanItemOut"][];
        };
        /**
         * PlanStatus
         * @description 一份 Import Plan 現在的位置（plan §2.3 的 `plans.status`）。
         *
         *     **它與 Job 狀態回答的是不同的問題**：Job 說的是那個 torrent 走到哪一站，Plan 說的是
         *     「這一份決定被採信到什麼程度」。一筆 `review` 的 Job 一定有一份 `pending_review` 的
         *     Plan，但一份 `preplan` 的 Plan 底下的 Job 可能還在下載。
         * @enum {string}
         */
        PlanStatus: "preplan" | "auto" | "pending_review" | "approved" | "rejected" | "applied" | "failed";
        /**
         * PlanSummary
         * @description 一份 Plan 的一句話（`plans.summary_json`，plan §2.3、票 11）。
         *
         *     存下來而不是每次數一遍：下載列表上一列 Job 只想說「12 個檔案要入庫、2 個等人看」，
         *     而那句話不該讓每一列都去掃一次 `plan_items`。
         *
         *     住在 `domain/` 的理由與 `MediaSnapshot` 一樣（plan §2.2 的同一條偏差）：`models` 拿它
         *     當一個 `*_json` 欄位的型別，`services` 算它，而 `api` 直接把它送出去——三層都要它，
         *     而 `api` 依契約不 import `models`（plan §1.3）。
         */
        PlanSummary: {
            /**
             * Files
             * @default 0
             */
            files?: number;
            /**
             * High
             * @default 0
             */
            high?: number;
            /**
             * Medium
             * @default 0
             */
            medium?: number;
            /**
             * Low
             * @default 0
             */
            low?: number;
            /**
             * Actions
             * @default {}
             */
            actions?: {
                [key: string]: number;
            };
            review_reason?: components["schemas"]["ReviewReason"] | null;
        };
        /**
         * PollerOut
         * @description 下載迴圈上一輪的結果（plan §3.2）。
         */
        PollerOut: {
            /** Checked At */
            checked_at: string | null;
            /** Failures */
            failures: number;
            /** Error */
            error: string;
            /** Interval Seconds */
            interval_seconds: number;
            /** Unknown Torrents */
            unknown_torrents: components["schemas"]["UnknownTorrentOut"][];
        };
        /** PreferenceDiffOut */
        PreferenceDiffOut: {
            /** Key */
            key: string;
            /** Current */
            current: string;
            /** Recommended */
            recommended: string;
            /** Differs */
            differs: boolean;
        };
        /**
         * Profile
         * @description Route 的命名與解析偏好（CONTEXT.md）。
         * @enum {string}
         */
        Profile: "standard" | "anime";
        /**
         * QbittorrentOut
         * @description 精靈第 4 步與設定頁的漂移還原共用（brief §16.3）。
         */
        QbittorrentOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            /** Version */
            version: string;
            /** Webapi Version */
            webapi_version: string;
            /** Supported */
            supported: boolean;
            /** Blocked */
            blocked: boolean;
            /** Reachable */
            reachable: boolean;
            /** Diffs */
            diffs: components["schemas"]["PreferenceDiffOut"][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Temp Path Warning */
            temp_path_warning: boolean;
            /** Sets Password */
            sets_password: boolean;
            /** Error */
            error: string;
        };
        /**
         * ReviewReason
         * @description 為什麼這一份 Plan 停下來等人（brief §5.2 的 `review_required(reason)`）。
         *
         *     封閉集合而不是一句話：畫面要照理由說出**下一步**（PRODUCT 原則 4），而三種理由的
         *     下一步不一樣——低信心要人指定季集，被 Route 擋下的 medium 只要人點頭，
         *     而「這一包沒有東西可以入庫」多半表示送錯了 torrent。
         * @enum {string}
         */
        ReviewReason: "low_confidence" | "medium_not_allowed" | "nothing_to_import" | "target_exists";
        /**
         * Role
         * @description 使用者角色。由 Jellyfin 的 `Policy.IsAdministrator` 決定（plan §11.1 T0.5）。
         * @enum {string}
         */
        Role: "admin" | "user";
        /**
         * RouteChoiceOut
         * @description 下拉裡的一條 Route。只會出現 `collection_type` 與這部作品相符的。
         *
         *     「劇集只進得了 tvshows 媒體庫」是領域規則（`domain.collection_type_for`），所以過濾在
         *     後端做，前端拿到的就是選得下去的那幾條——放前端會變成第二份實作。
         */
        RouteChoiceOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Slug */
            slug: string;
            collection_type: components["schemas"]["CollectionType"];
        };
        /** RouteOut */
        RouteOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Library */
            library: string;
            collection_type: components["schemas"]["CollectionType"];
            /** Target Path */
            target_path: string;
            /** Category */
            category: string;
            /** Save Path */
            save_path: string;
            profile: components["schemas"]["Profile"];
            /** Enabled */
            enabled: boolean;
            health: components["schemas"]["HealthStatus"];
            /** Checks */
            checks: components["schemas"]["StepOut"][];
            /** Cross Device */
            cross_device: boolean;
            /** Checked At */
            checked_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
        };
        /**
         * RouteSelectionIn
         * @description 既有 Jellyfin：勾起來的一個媒體庫與它的寫入目標。
         */
        RouteSelectionIn: {
            /** Library */
            library: string;
            /** Target Path */
            target_path: string;
            /** @default standard */
            profile?: components["schemas"]["Profile"];
        };
        /** RouteSetupOut */
        RouteSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Library Root */
            library_root: string;
            /** Complete Root */
            complete_root: string;
            /** Libraries */
            libraries: components["schemas"]["LibraryChoiceOut"][];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            /** Ready */
            ready: boolean;
            /** Completed */
            completed: boolean;
        };
        /** RoutesIn */
        RoutesIn: {
            /**
             * Selections
             * @default []
             */
            selections?: components["schemas"]["RouteSelectionIn"][];
        };
        /**
         * SearchOut
         * @description 一次搜尋的回應。
         *
         *     **拿不到索引站時仍然是 200**（與探索頁同一個道理，票 03）：「還沒接」「連不上」
         *     「憑證被拒」的下一步完全不同，做成 HTTP 錯誤的話前端只剩一個狀態碼分不出來。
         */
        SearchOut: {
            /** Rows */
            rows: components["schemas"]["SearchResultOut"][];
            /** Total */
            total: number;
            /** Discarded */
            discarded: number;
            /** Attempts */
            attempts: components["schemas"]["StepOut"][];
            problem: components["schemas"]["IndexerProblem"] | null;
            /** Detail */
            detail: string;
        };
        /**
         * SearchQueriesOut
         * @description 搜尋**之前**畫面要說的那句話：Berth 會拿這幾個名字去問。
         */
        SearchQueriesOut: {
            /** Queries */
            queries: string[];
        };
        /**
         * SearchResultOut
         * @description 結果表的一列（brief §13）。
         */
        SearchResultOut: {
            /** Title */
            title: string;
            /** Indexer */
            indexer: string;
            /** Size */
            size: number;
            /** Seeders */
            seeders: number | null;
            /** Info Url */
            info_url: string;
            /** Download Url */
            download_url: string;
            /** Key */
            key: string;
            /** Info Hash */
            info_hash: string;
            tags: components["schemas"]["TagsOut"];
            /** Season */
            season: number | null;
            /** Episode Start */
            episode_start: number | null;
            /** Episode End */
            episode_end: number | null;
            /** Whole Season */
            whole_season: boolean;
            strategy: components["schemas"]["MappingStrategy"] | null;
        };
        /**
         * SeasonOut
         * @description 一季。`season_number: 0` 是 Specials。
         */
        SeasonOut: {
            /** Season Number */
            season_number: number;
            /** Name */
            name: string;
            /** Episode Count */
            episode_count: number;
            /** Air Date */
            air_date: string | null;
            /** Episodes */
            episodes: components["schemas"]["EpisodeOut"][];
        };
        /** ServiceDetectionOut */
        ServiceDetectionOut: {
            kind: components["schemas"]["ServiceKind"];
            origin: components["schemas"]["ServiceOrigin"];
            reason: components["schemas"]["DetectionReason"];
            /** Detail */
            detail: string;
            /** Base Url */
            base_url: string;
            /** Configured */
            configured: boolean;
            /** Resolved */
            resolved: boolean;
        };
        /**
         * ServiceHealthOut
         * @description 健康頁與設定頁上一個服務那一列。
         */
        ServiceHealthOut: {
            kind: components["schemas"]["ServiceKind"];
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            status: components["schemas"]["HealthStatus"];
            /** Detail */
            detail: string;
            /** Error */
            error: string;
            /** Checked At */
            checked_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Failures */
            failures: number;
            /** Configured */
            configured: boolean;
            /** Drift */
            drift: string[];
            /** Banned */
            banned: boolean;
        };
        /**
         * ServiceKind
         * @description 精靈與健康檢查認得的三個外部服務。字串同時是 compose 的服務名。
         * @enum {string}
         */
        ServiceKind: "jellyfin" | "qbittorrent" | "prowlarr";
        /**
         * ServiceOrigin
         * @description 精靈第 2 步對單一服務的判定（plan §9.3）。逐服務判斷，沒有全局模式。
         * @enum {string}
         */
        ServiceOrigin: "bundled" | "existing" | "pending" | "timeout";
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Completed */
            completed: boolean;
            /** Current Step */
            current_step: number;
            /** Admin Created */
            admin_created: boolean;
            /** Admin Username */
            admin_username: string;
            /** Apply To Services */
            apply_to_services: boolean;
            /** Services */
            services: components["schemas"]["ServiceDetectionOut"][];
            /** Waited Seconds */
            waited_seconds: number;
            /** Window Seconds */
            window_seconds: number;
        };
        /** SkipIn */
        SkipIn: {
            /**
             * Skipped
             * @default true
             */
            skipped?: boolean;
        };
        /**
         * Source
         * @description 來源 token（brief §6.8）。BDRip / BluRay → `BD`，WEB-DL / WebRip → `WEB`。
         * @enum {string}
         */
        Source: "BD" | "WEB" | "DVD" | "HDTV" | "REMUX";
        /**
         * StepOut
         * @description 一條纜繩：精靈的一步，或一個 Route 的一項檢查。
         */
        StepOut: {
            /** Step */
            step: string;
            status: components["schemas"]["StepStatus"];
            /** Detail */
            detail: string;
            /** Error */
            error: string;
        };
        /**
         * StepStatus
         * @description 精靈裡一個步驟的結果。逐條纜繩顯示，所以是封閉集合。
         * @enum {string}
         */
        StepStatus: "ok" | "skipped" | "failed" | "running" | "pending";
        /**
         * TagsOut
         * @description 會進檔名的那幾格（brief §6.8）。
         *
         *     送結構化欄位而不是 `render()` 的那一串字：結果表要逐格顯示（來源一欄、解析度一欄），
         *     而字串只能整條印出來。畫面要那一串字時自己拼——拼法在 `Tags.render()`，不在這裡。
         */
        TagsOut: {
            source: components["schemas"]["Source"] | null;
            /** Resolution */
            resolution: string;
            /** Subs */
            subs: string[];
            /** Hardsub */
            hardsub: boolean;
            /** Group */
            group: string;
            /** Version */
            version: string;
            /** Edition */
            edition: string;
        };
        /**
         * TmdbProblem
         * @description 向 TMDB 要東西沒要到的四種樣子（票 03 的探索頁、票 04 的 Media 詳情）。
         *
         *     分成四種而不是一句錯誤訊息，是因為**下一步不同**：前兩種要使用者去精靈第 6 步處理憑證，
         *     `unreachable` 只能等或查網路，`not_found` 則是那個 id 本身不存在——重試一百次也一樣。
         *     封閉集合讓 UI 說得出那一步，而不是丟一個空畫面。
         *
         *     一個 enum 而不是每頁一個：兩頁問的是同一台服務，理由與下一步都一樣，
         *     各寫一份的話「憑證缺失要連到泊位 3」這條規則遲早會在其中一份裡走樣。
         * @enum {string}
         */
        TmdbProblem: "credential_missing" | "credential_rejected" | "unreachable" | "not_found";
        /** TmdbSetupOut */
        TmdbSetupOut: {
            /** Api Key Present */
            api_key_present: boolean;
            /** Verified */
            verified: boolean;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** TmdbTestIn */
        TmdbTestIn: {
            /** Api Key */
            api_key: string;
        };
        /**
         * UnknownTorrentOut
         * @description qBittorrent 上一個 Berth 沒有 Job 的 torrent（plan §3.2、票 10）。
         */
        UnknownTorrentOut: {
            /** Hash */
            hash: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** State */
            state: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_trending_api_discover_trending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
        };
    };
    get_popular_api_discover_popular_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
        };
    };
    get_search_api_discover_search_get: {
        parameters: {
            query: {
                /** @description 搜尋詞。空白的查詢回空清單而不是錯誤。 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_events_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_root_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    read_detail_api_health_detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    post_check_api_health_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    get_jobs_api_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
        };
    };
    post_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreatedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_api_jobs__job_hash__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobEventOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_replan_api_jobs__job_hash__replan_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_retry_api_jobs__job_hash__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_media_api_media__media_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_refresh_api_media__media_id__refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                media_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_plans__plan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                plan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_queries_api_search_queries_get: {
        parameters: {
            query: {
                /** @description `tv:<tmdb>` / `movie:<tmdb>`。 */
                media: string;
                /** @description 換這條 Route 的 profile 算一次（anime 多兩個季號變體）。 */
                route?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchQueriesOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_api_search_get: {
        parameters: {
            query: {
                /** @description `tv:<tmdb>` / `movie:<tmdb>`。 */
                media: string;
                /** @description 自己打的關鍵字。有值時取代作品的各個標題，只問這一個。 */
                q?: string;
                /** @description **這一輪搜尋的偏好，不是承諾**（票 04b）：只用來決定 anime profile 要不要加季號變體，不寫進 `media`，也不代表之後一定送到那條 Route。 */
                route?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_services_api_settings_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    post_service_test_api_settings_services__kind__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qbittorrent_diff_api_settings_qbittorrent_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    post_qbittorrent_apply_api_settings_qbittorrent_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    get_status_api_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    post_admin_api_setup_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_detect_api_setup_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DetectIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_service_api_setup_services__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ServiceKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jellyfin_api_setup_jellyfin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    post_jellyfin_bootstrap_api_setup_jellyfin_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    post_jellyfin_connect_api_setup_jellyfin_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JellyfinConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_jellyfin_library_path_api_setup_jellyfin_libraries_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryPathIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_jellyfin_plugin_api_setup_jellyfin_plugin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    get_qbittorrent_diff_api_setup_qbittorrent_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    post_qbittorrent_apply_api_setup_qbittorrent_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    get_indexers_api_setup_indexers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
        };
    };
    post_indexers_apply_api_setup_indexers_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_indexers_connect_api_setup_indexers_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_indexers_skip_api_setup_indexers_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tmdb_api_setup_tmdb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TmdbSetupOut"];
                };
            };
        };
    };
    post_tmdb_test_api_setup_tmdb_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmdbTestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TmdbSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routes_api_setup_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSetupOut"];
                };
            };
        };
    };
    post_routes_api_setup_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoutesIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_complete_api_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
}
