/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Login */
        post: operations["post_login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Logout
         * @description 一律成功。session 早就過期的人也該把瀏覽器裡那張 cookie 清掉。
         */
        post: operations["post_logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Me
         * @description 門禁已經擋掉沒有 session 的請求，所以走到這裡一定有人。
         */
        get: operations["get_me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/trending": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trending */
        get: operations["get_trending_api_discover_trending_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/popular": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Popular */
        get: operations["get_popular_api_discover_popular_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/discover/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Search */
        get: operations["get_search_api_discover_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root Health */
        get: operations["read_root_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Detail
         * @description 上一輪的結果，逐服務與逐 Route。**不連任何服務**（`POST /health/check` 才連）。
         */
        get: operations["read_detail_api_health_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Check
         * @description 立刻重跑四項檢查（plan §3.2 的「+ 手動」）。迴圈跑的是同一支命令。
         */
        post: operations["post_check_api_health_check_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Services
         * @description 三個服務現在的樣子。與健康頁同一份形狀——同一件事不該有兩種說法。
         */
        get: operations["get_services_api_settings_services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/services/{kind}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Service Test
         * @description 「測試連線」：只重測這一個服務，其餘三項的結果留著（票 10）。
         */
        post: operations["post_service_test_api_settings_services__kind__test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/qbittorrent/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qbittorrent Diff
         * @description 現值與建議值的逐鍵差異——與精靈第 4 步問的是同一個問題。
         */
        get: operations["get_qbittorrent_diff_api_settings_qbittorrent_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings/qbittorrent/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Qbittorrent Apply
         * @description 「還原建議設定」。只寫有差異的鍵，跑的是精靈第 4 步的同一支命令。
         */
        post: operations["post_qbittorrent_apply_api_settings_qbittorrent_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Admin */
        post: operations["post_admin_api_setup_admin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Detect */
        post: operations["post_detect_api_setup_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/services/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Service
         * @description 既有服務的「測試連線」：存下連線資訊再連一次（plan §9.3 第 2 步）。
         */
        post: operations["post_service_api_setup_services__kind__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Jellyfin
         * @description 不連線，只回存下來的狀態。bootstrap 進行中前端輪詢這一支看序列走到哪裡。
         */
        get: operations["get_jellyfin_api_setup_jellyfin_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Bootstrap
         * @description 套件內路徑：跑完 plan §9.4 的九步。重按只補做還沒做的那幾步。
         */
        post: operations["post_jellyfin_bootstrap_api_setup_jellyfin_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Connect
         * @description 既有路徑：登入、建立 API key、列出媒體庫（plan §9.5）。
         */
        post: operations["post_jellyfin_connect_api_setup_jellyfin_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/libraries/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Library Path
         * @description 既有路徑的「加入 Berth 路徑」。舊路徑原地不動（brief §16.4）。
         *
         *     失敗不是 4xx/5xx，而是回一條 `failed` 的 `libraries` 步驟——畫面靠它顯示原文與手動步驟。
         */
        post: operations["post_jellyfin_library_path_api_setup_jellyfin_libraries_paths_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/jellyfin/plugin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Jellyfin Plugin
         * @description 既有路徑的「安裝 MergeVersions」。**會重啟 Jellyfin**，所以 UI 要二次確認。
         */
        post: operations["post_jellyfin_plugin_api_setup_jellyfin_plugin_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/qbittorrent/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Qbittorrent Diff
         * @description 現值與建議值的逐鍵差異。連得到才有內容，連不到就是 `reachable=false` 加原文。
         */
        get: operations["get_qbittorrent_diff_api_setup_qbittorrent_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/qbittorrent/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Qbittorrent Apply
         * @description 套用建議偏好。只寫有差異的鍵；勾了「同一組帳密」才順便設 WebUI 密碼。
         */
        post: operations["post_qbittorrent_apply_api_setup_qbittorrent_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Indexers */
        get: operations["get_indexers_api_setup_indexers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Indexers Apply
         * @description 套件內路徑：勾起來的站逐個加進 Prowlarr，逐站回報成敗。
         *
         *     對既有的索引站回 422：那是使用者自己的服務，Berth 只做檢查（brief §16.4）。
         */
        post: operations["post_indexers_apply_api_setup_indexers_apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Indexers Connect
         * @description 既有路徑的「測試」。測不過也存，使用者才能改一個欄位再按一次。
         */
        post: operations["post_indexers_connect_api_setup_indexers_connect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/indexers/skip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Indexers Skip */
        post: operations["post_indexers_skip_api_setup_indexers_skip_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/tmdb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tmdb */
        get: operations["get_tmdb_api_setup_tmdb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/tmdb/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Tmdb Test
         * @description 先存再測。`configuration` 回得出來就證明這把憑證有效。
         *
         *     **沒有 `/tmdb/skip`**：這一步是閘門，測不過就走不到第 7 步（票 02b）。
         */
        post: operations["post_tmdb_test_api_setup_tmdb_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/routes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Routes
         * @description 不連線，只回媒體庫清單與已經建好的 Route（含上一輪的檢查結果）。
         */
        get: operations["get_routes_api_setup_routes_get"];
        put?: never;
        /**
         * Post Routes
         * @description 建立 Route，並立刻建 category 與跑三項檢查（plan §9.5）。
         *
         *     檢查失敗**不是** 4xx：它是這一步的結果，逐項回在 `routes[].checks` 裡，畫面靠它顯示
         *     原文與該補哪個掛載。4xx 只留給「這個選擇本身無效」（不存在的媒體庫、不是它的路徑）。
         */
        post: operations["post_routes_api_setup_routes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/setup/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Complete
         * @description 第 8 步：寫下 `settings.setup.completed`。**寫完這一支就要登入才進得來**（票 07）。
         */
        post: operations["post_complete_api_setup_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminIn */
        AdminIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Apply To Services
             * @default true
             */
            apply_to_services?: boolean;
        };
        /**
         * CollectionType
         * @description Jellyfin 媒體庫的類型；沿用 Jellyfin 的字串（brief §4.3）。
         * @enum {string}
         */
        CollectionType: "movies" | "tvshows";
        /**
         * ConnectIn
         * @description 既有服務的連線表單。每個服務只用得到其中幾個欄位。
         */
        ConnectIn: {
            /** Base Url */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key?: string;
            /**
             * Username
             * @default
             */
            username?: string;
            /**
             * Password
             * @default
             */
            password?: string;
        };
        /** DetectIn */
        DetectIn: {
            /**
             * Restart
             * @default false
             */
            restart?: boolean;
        };
        /**
         * DetectionReason
         * @description 判定的理由。UI 逐服務顯示，所以是封閉集合而不是自由文字。
         * @enum {string}
         */
        DetectionReason: "setup_pending" | "setup_completed" | "anonymous_ok" | "auth_required" | "no_indexers" | "has_indexers" | "api_key_missing" | "not_deployed" | "unreachable" | "protocol_mismatch" | "connected";
        /**
         * DiscoverItemOut
         * @description 牆上的一格。
         */
        DiscoverItemOut: {
            /** Id */
            id: string;
            /** Tmdb Id */
            tmdb_id: number;
            kind: components["schemas"]["MediaKind"];
            /** Title */
            title: string;
            /** Title En */
            title_en: string;
            /** Year */
            year: number | null;
            /** Poster Url */
            poster_url: string;
            /** Tracked */
            tracked: boolean;
        };
        /**
         * DiscoverOut
         * @description 一個 feed 的回應。
         *
         *     **失敗也是 200**：一頁上有三個 feed，其中一個拿不到 TMDB 時另外兩個照樣畫得出來，
         *     而畫面要說得出下一步。把它做成 HTTP 錯誤的話，前端只剩一個狀態碼，分不出
         *     「還沒填憑證」與「TMDB 連不上」——那兩件事的修法完全不同（票 03 驗收）。
         */
        DiscoverOut: {
            /** Items */
            items: components["schemas"]["DiscoverItemOut"][];
            problem: components["schemas"]["DiscoverProblem"] | null;
            /** Detail */
            detail: string;
        };
        /**
         * DiscoverProblem
         * @description 探索頁拿不到 TMDB 的三種樣子（票 03）。
         *
         *     分成三種而不是一句錯誤訊息，是因為**下一步不同**：前兩種要使用者去精靈第 6 步處理憑證，
         *     第三種只能等或查網路。封閉集合讓 UI 說得出那一步，而不是丟一個空畫面。
         * @enum {string}
         */
        DiscoverProblem: "credential_missing" | "credential_rejected" | "unreachable";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Setup Completed */
            setup_completed: boolean;
        };
        /**
         * HealthDetailOut
         * @description 四項檢查的明細。健康頁與設定頁讀的是同一份——同一件事不該有兩種說法。
         */
        HealthDetailOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Checked At */
            checked_at: string | null;
            /** Interval Seconds */
            interval_seconds: number;
            /** Services */
            services: components["schemas"]["ServiceHealthOut"][];
            routes_status: components["schemas"]["HealthStatus"];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
        };
        /**
         * HealthStatus
         * @description Route 或服務的最後檢查結果；`UNKNOWN` 表示尚未檢查過。
         * @enum {string}
         */
        HealthStatus: "unknown" | "ok" | "failed";
        /** IndexerApplyIn */
        IndexerApplyIn: {
            /**
             * Indexers
             * @default []
             */
            indexers?: string[];
        };
        /**
         * IndexerConnectIn
         * @description 既有路徑：Prowlarr 位址 + key，或任意 Torznab 端點 + key。
         */
        IndexerConnectIn: {
            kind: components["schemas"]["IndexerKind"];
            /** Base Url */
            base_url: string;
            /**
             * Api Key
             * @default
             */
            api_key?: string;
        };
        /**
         * IndexerKind
         * @description 第 5 步接索引站的兩種方式（plan §8.4、§9.3 第 5 步）。
         * @enum {string}
         */
        IndexerKind: "prowlarr" | "torznab";
        /** IndexerOptionOut */
        IndexerOptionOut: {
            /** Definition Name */
            definition_name: string;
            /** Name */
            name: string;
            /** Privacy */
            privacy: string;
            /** Present */
            present: boolean;
        };
        /** IndexerSetupOut */
        IndexerSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            kind: components["schemas"]["IndexerKind"];
            /** Base Url */
            base_url: string;
            /** Api Key Present */
            api_key_present: boolean;
            /** Reachable */
            reachable: boolean;
            /** Options */
            options: components["schemas"]["IndexerOptionOut"][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Skipped */
            skipped: boolean;
            /** Sets Password */
            sets_password: boolean;
            /** Error */
            error: string;
        };
        /**
         * JellyfinConnectIn
         * @description 既有 Jellyfin 的管理員帳密。只用來換 API key，不存下來。
         */
        JellyfinConnectIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** JellyfinSetupOut */
        JellyfinSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            /** Api Key Present */
            api_key_present: boolean;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Merge Versions Installed */
            merge_versions_installed: boolean;
            /** Merge Movies Task Id */
            merge_movies_task_id: string;
            /** Merge Episodes Task Id */
            merge_episodes_task_id: string;
        };
        /** LibraryChoiceOut */
        LibraryChoiceOut: {
            /** Name */
            name: string;
            /** Collection Type */
            collection_type: string;
            /** Locations */
            locations: string[];
            /** Berth Path */
            berth_path: string;
            /** Has Berth Path */
            has_berth_path: boolean;
            /** Uses Tvdb */
            uses_tvdb: boolean;
            /** Supported */
            supported: boolean;
            /** Selected */
            selected: boolean;
            /** Target Path */
            target_path: string;
            profile: components["schemas"]["Profile"];
        };
        /** LibraryOut */
        LibraryOut: {
            /** Name */
            name: string;
            /** Collection Type */
            collection_type: string;
            /** Locations */
            locations: string[];
            /** Metadata Fetchers */
            metadata_fetchers: string[];
            /** Uses Tvdb */
            uses_tvdb: boolean;
            /** Berth Path */
            berth_path: string;
            /** Has Berth Path */
            has_berth_path: boolean;
        };
        /** LibraryPathIn */
        LibraryPathIn: {
            /** Library */
            library: string;
        };
        /**
         * LoginIn
         * @description 帳密**不加約束、也不設必填**：少一個欄位就會是 422，而 422 與 401 分得出來就是一個
         *     可以拿來試探的差別。空的與錯的一律交給 services 拒絕，回同一個 401。
         *
         *     422 的回應本身不帶收到的值——那是 `api/errors.py` 的事。
         */
        LoginIn: {
            /**
             * Username
             * @default
             */
            username?: string;
            /**
             * Password
             * @default
             */
            password?: string;
        };
        /**
         * MeOut
         * @description 使用者可見的身分。id 與 Jellyfin user id 都不外流——UI 用不到。
         */
        MeOut: {
            /** Name */
            name: string;
            role: components["schemas"]["Role"];
        };
        /**
         * MediaKind
         * @description 一個作品是劇集還是電影（plan §2.2）。
         *
         *     字串同時是三個東西：`media.id` 的前綴（`tv:1234`）、TMDB `search/multi` 回的
         *     `media_type`，以及 TMDB 那兩組端點的路徑段（`trending/tv/week`、`movie/popular`）。
         *     三者一致不是巧合——沿用 provider 的字串就不必維護一張對照表。
         * @enum {string}
         */
        MediaKind: "tv" | "movie";
        /** PreferenceDiffOut */
        PreferenceDiffOut: {
            /** Key */
            key: string;
            /** Current */
            current: string;
            /** Recommended */
            recommended: string;
            /** Differs */
            differs: boolean;
        };
        /**
         * Profile
         * @description Route 的命名與解析偏好（CONTEXT.md）。
         * @enum {string}
         */
        Profile: "standard" | "anime";
        /**
         * QbittorrentOut
         * @description 精靈第 4 步與設定頁的漂移還原共用（brief §16.3）。
         */
        QbittorrentOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            /** Version */
            version: string;
            /** Webapi Version */
            webapi_version: string;
            /** Supported */
            supported: boolean;
            /** Blocked */
            blocked: boolean;
            /** Reachable */
            reachable: boolean;
            /** Diffs */
            diffs: components["schemas"]["PreferenceDiffOut"][];
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /** Temp Path Warning */
            temp_path_warning: boolean;
            /** Sets Password */
            sets_password: boolean;
            /** Error */
            error: string;
        };
        /**
         * Role
         * @description 使用者角色。由 Jellyfin 的 `Policy.IsAdministrator` 決定（plan §11.1 T0.5）。
         * @enum {string}
         */
        Role: "admin" | "user";
        /** RouteOut */
        RouteOut: {
            /** Slug */
            slug: string;
            /** Name */
            name: string;
            /** Library */
            library: string;
            collection_type: components["schemas"]["CollectionType"];
            /** Target Path */
            target_path: string;
            /** Category */
            category: string;
            /** Save Path */
            save_path: string;
            profile: components["schemas"]["Profile"];
            /** Enabled */
            enabled: boolean;
            health: components["schemas"]["HealthStatus"];
            /** Checks */
            checks: components["schemas"]["StepOut"][];
            /** Cross Device */
            cross_device: boolean;
            /** Checked At */
            checked_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
        };
        /**
         * RouteSelectionIn
         * @description 既有 Jellyfin：勾起來的一個媒體庫與它的寫入目標。
         */
        RouteSelectionIn: {
            /** Library */
            library: string;
            /** Target Path */
            target_path: string;
            /** @default standard */
            profile?: components["schemas"]["Profile"];
        };
        /** RouteSetupOut */
        RouteSetupOut: {
            origin: components["schemas"]["ServiceOrigin"];
            /** Library Root */
            library_root: string;
            /** Complete Root */
            complete_root: string;
            /** Libraries */
            libraries: components["schemas"]["LibraryChoiceOut"][];
            /** Routes */
            routes: components["schemas"]["RouteOut"][];
            /** Ready */
            ready: boolean;
            /** Completed */
            completed: boolean;
        };
        /** RoutesIn */
        RoutesIn: {
            /**
             * Selections
             * @default []
             */
            selections?: components["schemas"]["RouteSelectionIn"][];
        };
        /** ServiceDetectionOut */
        ServiceDetectionOut: {
            kind: components["schemas"]["ServiceKind"];
            origin: components["schemas"]["ServiceOrigin"];
            reason: components["schemas"]["DetectionReason"];
            /** Detail */
            detail: string;
            /** Base Url */
            base_url: string;
            /** Configured */
            configured: boolean;
            /** Resolved */
            resolved: boolean;
        };
        /**
         * ServiceHealthOut
         * @description 健康頁與設定頁上一個服務那一列。
         */
        ServiceHealthOut: {
            kind: components["schemas"]["ServiceKind"];
            origin: components["schemas"]["ServiceOrigin"];
            /** Base Url */
            base_url: string;
            status: components["schemas"]["HealthStatus"];
            /** Detail */
            detail: string;
            /** Error */
            error: string;
            /** Checked At */
            checked_at: string | null;
            /** Last Ok At */
            last_ok_at: string | null;
            /** Failures */
            failures: number;
            /** Configured */
            configured: boolean;
            /** Drift */
            drift: string[];
        };
        /**
         * ServiceKind
         * @description 精靈與健康檢查認得的三個外部服務。字串同時是 compose 的服務名。
         * @enum {string}
         */
        ServiceKind: "jellyfin" | "qbittorrent" | "prowlarr";
        /**
         * ServiceOrigin
         * @description 精靈第 2 步對單一服務的判定（plan §9.3）。逐服務判斷，沒有全局模式。
         * @enum {string}
         */
        ServiceOrigin: "bundled" | "existing" | "pending" | "timeout";
        /** SetupStatusOut */
        SetupStatusOut: {
            /** Completed */
            completed: boolean;
            /** Current Step */
            current_step: number;
            /** Admin Created */
            admin_created: boolean;
            /** Admin Username */
            admin_username: string;
            /** Apply To Services */
            apply_to_services: boolean;
            /** Services */
            services: components["schemas"]["ServiceDetectionOut"][];
            /** Waited Seconds */
            waited_seconds: number;
            /** Window Seconds */
            window_seconds: number;
        };
        /** SkipIn */
        SkipIn: {
            /**
             * Skipped
             * @default true
             */
            skipped?: boolean;
        };
        /**
         * StepOut
         * @description 一條纜繩：精靈的一步，或一個 Route 的一項檢查。
         */
        StepOut: {
            /** Step */
            step: string;
            status: components["schemas"]["StepStatus"];
            /** Detail */
            detail: string;
            /** Error */
            error: string;
        };
        /**
         * StepStatus
         * @description 精靈裡一個步驟的結果。逐條纜繩顯示，所以是封閉集合。
         * @enum {string}
         */
        StepStatus: "ok" | "skipped" | "failed" | "running" | "pending";
        /** TmdbSetupOut */
        TmdbSetupOut: {
            /** Api Key Present */
            api_key_present: boolean;
            /** Verified */
            verified: boolean;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
        };
        /** TmdbTestIn */
        TmdbTestIn: {
            /** Api Key */
            api_key: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    post_login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
        };
    };
    get_trending_api_discover_trending_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
        };
    };
    get_popular_api_discover_popular_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
        };
    };
    get_search_api_discover_search_get: {
        parameters: {
            query: {
                /** @description 搜尋詞。空白的查詢回空清單而不是錯誤。 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoverOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_root_health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    read_detail_api_health_detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    post_check_api_health_check_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    get_services_api_settings_services_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
        };
    };
    post_service_test_api_settings_services__kind__test_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_qbittorrent_diff_api_settings_qbittorrent_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    post_qbittorrent_apply_api_settings_qbittorrent_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    get_status_api_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
    post_admin_api_setup_admin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_detect_api_setup_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DetectIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_service_api_setup_services__kind__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["ServiceKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_jellyfin_api_setup_jellyfin_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    post_jellyfin_bootstrap_api_setup_jellyfin_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    post_jellyfin_connect_api_setup_jellyfin_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JellyfinConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_jellyfin_library_path_api_setup_jellyfin_libraries_paths_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LibraryPathIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_jellyfin_plugin_api_setup_jellyfin_plugin_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JellyfinSetupOut"];
                };
            };
        };
    };
    get_qbittorrent_diff_api_setup_qbittorrent_diff_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    post_qbittorrent_apply_api_setup_qbittorrent_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QbittorrentOut"];
                };
            };
        };
    };
    get_indexers_api_setup_indexers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
        };
    };
    post_indexers_apply_api_setup_indexers_apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerApplyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_indexers_connect_api_setup_indexers_connect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IndexerConnectIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_indexers_skip_api_setup_indexers_skip_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkipIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tmdb_api_setup_tmdb_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TmdbSetupOut"];
                };
            };
        };
    };
    post_tmdb_test_api_setup_tmdb_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TmdbTestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TmdbSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_routes_api_setup_routes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSetupOut"];
                };
            };
        };
    };
    post_routes_api_setup_routes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoutesIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RouteSetupOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_complete_api_setup_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusOut"];
                };
            };
        };
    };
}
